### ISSUE TITLE
NoHistoryException

### ISSUE THREAD

**Issue by borwick** [gauteh/gmailieer#102]
Hello! I just received a NoHistoryException for the first time since starting to use gmailieer a few weeks ago. I addressed this by running `gmi pull -f`.

If this happens again, is there any debugging/diagnostic information I can provide to investigate what may have happened?

Thanks! Also thanks very much for gmailieer it is great!

**Comment by gauteh** [comment]
Hi,

I unfortunately don't know what is going on, I posted this question ages ago: https://stackoverflow.com/questions/44276743/gmail-api-users-history-list-returns-nextpagetoken-but-no-history-field, but it does not seem to have attained the attention of google. 

It seems it is almost safe to just ignore it and treat it as end of history, but I'd rather fail than cause someone to miss emails.

Did this happen after a long time without syncing? Maybe it is related to the number of history items.

Regards, Gaute

**Comment by borwick** [comment]
It had been ~1 day since my previous synchronization. There is a _chance_ that I called gmi more than once at the same time. Sure, I think the failure mode is fine. If I see this again I'll try to pay attention to anything that may have triggered it.
