### ISSUE TITLE
Another data point for sync time?

### ISSUE THREAD

**Issue by alown** [gauteh/gmailieer#103]
Hi,

Not sure if you are happy for me to edit the wiki directly, but thought you might want another data point for sync time as it is outside the range currently shown. Not sure we can conclude much from size/number of messages to sync time though...

A fresh pull from one of my main mailboxes conducted yesterday, no recent gmi/imap full syncs so no anticipated throttling, but I didn't used a custom API key. Disk size of the result (excluding notmuch index) is ~6.9GBytes.
```
pull: full synchronization (no previous synchronization state)
fetching messages: 224068it [07:42, 408.42it/s]                                                        receiving content: 100%|█████████████████████████████████████| 224068/224068 [4:17:44<00:00, 14.49it/s]
receiving metadata: everything up-to-date.
current historyId: 13633760, current revision: 683314
```

I can also provide a little more context for the data I provided in #88/20: there were no recent gmi/imap full syncs, and the end result on disk is ~400Mbytes.

Thanks,
alown

**Comment by gauteh** [comment]
Thanks! Very happy with you editing the wiki directly yourself!

About 4h for 200k messages?

fre. 1. mar. 2019 kl. 00:53 skrev Ali Lown <notifications@github.com>:

**Comment by gauteh** [comment]
Added, thanks.
