### ISSUE TITLE
http.client.RemoteDisconnected not handled

### ISSUE THREAD

**Issue by espindola** [gauteh/gmailieer#12]
I got this while running gmi pull

[log.txt](https://github.com/gauteh/gmailieer/files/949907/log.txt)

**Comment by gauteh** [comment]
Rafael Ávila de Espíndola writes on april 23, 2017 20:17:
> I got this while running gmi pull
> [...]

>    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
>socket.gaierror: [Errno -2] Name or service not known

Looks like your internet connection might have dropped? I don't know if
there is anything better we can do than just fail.

**Comment by gauteh** [comment]
I will close this, looks like a dropped net connection.

**Comment by espindola** [comment]
It would still be better to convert the exception to a user friendly error, no?

On April 24, 2017 3:57:41 PM EDT, Gaute Hope <notifications@github.com> wrote:
>I will close this, looks like a dropped net connection.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gauteh/gmailieer/issues/12#issuecomment-296804974

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gauteh** [comment]
Rafael Ávila de Espíndola writes on april 25, 2017 1:41:
> It would still be better to convert the exception to a user friendly error, no?

Agreed, do you have the chance to look into it? I don't think I will
have the time in the immediate future.
