### ISSUE TITLE
Is this a replacement of abunchoftags?

### ISSUE THREAD

**Issue by aureooms** [gauteh/gmailieer#13]
?

**Comment by gauteh** [comment]
Aurélien Ooms writes on april 27, 2017 14:20:
> ?

Yes, it is a standalone program: it synchronizes the e-mail content as
well, so you do not use it with offlineimap.

**Comment by aureooms** [comment]
So it also replaces offlineimap ?

**Comment by gauteh** [comment]
Aurélien Ooms writes on april 27, 2017 20:09:
> So it also replaces offlineimap ? 

For Gmail, it does not add or remove messages on the remote - only
change labels. It uses the gmail api, and is much faster (after initial
sync).

**Comment by aureooms** [comment]
Ok. Nice work! I have to quit offlineimap, it is totally unreliable.

**Comment by androclus** [comment]
It might be helpful to mention that offlineimap is not needed or used (nor isync/mbsync), then, in the README.md, as I spent a lot of time trying to figure that out.

**Comment by julian-klode** [comment]
It states "This program can pull email and labels (and changes to labels) from your GMail account and store them locally in a maildir" - it literally says that it pulls emails, and it also says "The changes to tags in the notmuch database may be pushed back remotely to your GMail account." - so it says that it pushes the emails back. How is that not obvious enough?

**Comment by gauteh** [comment]
Actually, only labels are pushed back.

**Comment by julian-klode** [comment]
Yes, yes, sorry.

**Comment by gauteh** [comment]
I think this is settled now.
