### ISSUE TITLE
After first pull, all emails have the inbox and unread labels

### ISSUE THREAD

**Issue by aureooms** [gauteh/gmailieer#15]
Other labels are fine though. Did I do something wrong? Only 2 emails do not have the inbox and unread labels.

**Comment by aureooms** [comment]
Ah! I have

```
[new]
tags=unread;inbox;
```
in notmuch's config. Should probably remove it.

**Comment by aureooms** [comment]
Which other notmuch config entries need to be modified? For example, does synchronize_flags conflict with gmailieer?

```
[maildir]
synchronize_flags=true
```

**Comment by gauteh** [comment]
Aurélien Ooms writes on april 28, 2017 20:41:
> Which other notmuch config entries need to be modified? For example, does synchronize_flags conflict with gmailieer?

synchronize_flags is honored, but it does not have any effect on the
tags. new.tags are all added, that should be documented better in the
README. the tag 'new' is not synchronized to remote, so I usually have
that in new.tags and then you can set 'unread' or 'inbox' in post-new
hook in notmuch for other accounts if you need to.

**Comment by gauteh** [comment]
Gaute Hope writes on april 28, 2017 21:50:
> Aurélien Ooms writes on april 28, 2017 20:41:
>> Which other notmuch config entries need to be modified? For example, does synchronize_flags conflict with gmailieer?
> 
> synchronize_flags is honored, but it does not have any effect on the
> tags. new.tags are all added, that should be documented better in the
> README. the tag 'new' is not synchronized to remote, so I usually have
> that in new.tags and then you can set 'unread' or 'inbox' in post-new
> hook in notmuch for other accounts if you need to.

By the way, you should be able to do a `gmi pull -f` to do a full
synchronization, overwriting the local changes, to get rid of the
unread/inbox labels that should not be there.

**Comment by aureooms** [comment]
Nice! I'll try that next time the flags are out of sync.
