### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by espindola** [gauteh/gmailieer#23]
I got the following backtrace during a sync

[log.txt](https://github.com/gauteh/gmailieer/files/1015015/log.txt)

**Comment by gauteh** [comment]
That must be a notmuch / notmuch Python bindings bug.


fre. 19. mai 2017 kl. 19.14 skrev Rafael Ávila de Espíndola <
notifications@github.com>:

**Comment by gauteh** [comment]
I am going to close this one as well, I believe it is a notmuch bug.
