### ISSUE TITLE
<HttpError 400 when requesting https://www.googleapis.com/gmail/v1/users/julian.klode%40gmail.com/messages/15c69db4486d0718/modify?alt=json returned "Can only add on e of: INBOX, SPAM, TRASH">     

### ISSUE THREAD

**Issue by julian-klode** [gauteh/gmailieer#26]
If I locally tag a mail as both +inbox and +trash (which makes no sense, really), the sync fails. gmailieer should instead just drop the inbox tag and add the trash tag I guess.

**Comment by julian-klode** [comment]
See pull request #27

**Comment by gauteh** [comment]
Seems like the best approach, do you have any reference for the API behavior? Also, I guess we should print a warning. The most defensive approach would be to drop either TRASH or SPAM labels, but I don't think it is the most frequently desired behavior.

**Comment by julian-klode** [comment]
I don't think there's any reference, only the error message (and well it makes sense). Could make the handling dependant on the excluded tags in the notmuch config. If spam and trash are excluded, do what I did; otherwise apply inbox again (that would match the visible local behaviour).

**Comment by gauteh** [comment]
Hm ok, seems too complicated. I guess we should just mirror gmails behavior like you do now. But:

- [ ] Print warning
- [ ] Add note to Caveats section of README.md

**Comment by julian-klode** [comment]
Pull request updated.

**Comment by gauteh** [comment]
Thanks, for some reason I never receive notifications from this issue.
