### ISSUE TITLE
Label name exists or conflicts

### ISSUE THREAD

**Issue by maxking** [gauteh/gmailieer#29]
```
Traceback (most recent call last):
  File "/home/maxking/Documents/gmailieer/lieer/remote.py", line 569, in __create_label__
    lr = self.service.users ().labels ().create (userId = self.account, body = label).execute ()
  File "/usr/local/lib/python3.5/dist-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/googleapiclient/http.py", line 840, in execute
    raise HttpError(resp, content, uri=self.uri)
googleapiclient.errors.HttpError: <HttpError 409 when requesting https://www.googleapis.com/gmail/v1/users/raj.abhilash1%40gmail.com/labels?alt=json returned "Label name exists or conflicts">
```

If a local label exists, it tries to create a create same label remotely and fails

**Comment by gauteh** [comment]
Abhilash Raj writes on juni 7, 2017 4:49:
> ```
> Traceback (most recent call last):
>   File "/home/maxking/Documents/gmailieer/lieer/remote.py", line 569, in __create_label__
>     lr = self.service.users ().labels ().create (userId = self.account, body = label).execute ()
>   File "/usr/local/lib/python3.5/dist-packages/oauth2client/_helpers.py", line 133, in positional_wrapper
>     return wrapped(*args, **kwargs)
>   File "/usr/local/lib/python3.5/dist-packages/googleapiclient/http.py", line 840, in execute
>     raise HttpError(resp, content, uri=self.uri)
> googleapiclient.errors.HttpError: <HttpError 409 when requesting https://www.googleapis.com/gmail/v1/users/raj.abhilash1%40gmail.com/labels?alt=json returned "Label name exists or conflicts">
> ```

Could this be a label with different case or a reserved label?

I get all the remote labels by using: https://developers.google.com/gmail/api/v1/reference/users/labels/list (there is no paging here, so they should all be retrieved). Or could the label somehow have been created while gmailieer was running?

Does the problem persist if you try again?

- gaute

**Comment by maxking** [comment]
Actually, this happened because I had some tag rules in notmuch that had same names as gmail because my previous imap client wouldn't sync tags. 
So, it would just try to push those tags over to gmail even if they existed over there. 

Does that make sense?

And thanks alot for your prompt response :)

**Comment by gauteh** [comment]
Abhilash Raj writes on juni 7, 2017 10:54:
> Actually, this happened because I had some tag rules in notmuch that had same names as gmail because my previous imap client wouldn't sync tags. 
> So, it would just try to push those tags over to gmail even if they existed over there. 
> 
> Does that make sense?

Sort of :) gmailieer fetches all the tags from the remote; you can test
this by doing:

  $ gmi pull -t

so if the tag/label already existed remotely gmailieer should not try to
re-create it, even if no messages have the label assigned remotely.
There might be some label-rules at the gmail side that we accidently
violated though.

**Comment by maxking** [comment]
Cool, I think I will just delete my mail dir and then fetch filter/tags from gmail.

Thanks!

**Comment by gauteh** [comment]
Abhilash Raj writes on juni 8, 2017 3:19:
> Cool, I think I will just delete my mail dir and then fetch filter/tags from gmail.
> 
> Thanks!
> 

No problem, please back up everything!

**Comment by maxking** [comment]
Yeah, I accidentally ended up removing `inbox` tags for most recent 40-50 messages in my Gmail so they don't show up where they should. So backups +1
