### ISSUE TITLE
Unhandled exception: cannot reduce request any further

### ISSUE THREAD

**Issue by espindola** [gauteh/gmailieer#3]
During the initial clone I got this error:

[log.txt](https://github.com/gauteh/gmailieer/files/882359/log.txt)

**Comment by gauteh** [comment]
Rafael Ávila de Espíndola writes on mars 30, 2017 15:07:
> During the initial clone I got this error:
> 
> 
> [log.txt](https://github.com/gauteh/gmailieer/files/882359/log.txt)

Looks like a UserRateError, might have to just wait a bit before you try
again. I guess ideally we should introduce a time delay between
requests.

gmi will detect existing messages, and only fetch message content that
are missing.

**Comment by espindola** [comment]
>
> > [log.txt](https://github.com/gauteh/gmailieer/files/882359/log.txt)
>
> Looks like a UserRateError, might have to just wait a bit before you try
> again. I guess ideally we should introduce a time delay between
> requests.
>
> gmi will detect existing messages, and only fetch message content that
> are missing.
>

Yes, starting again seems to work. It would just be nice for the raw
exception to be converted to a plain error message.

Cheers,
Rafael

**Comment by gauteh** [comment]
You can try #4

**Comment by gauteh** [comment]
Fixed in #8
