### ISSUE TITLE
.gmailieer.json destroyed when running out of space

### ISSUE THREAD

**Issue by julian-klode** [gauteh/gmailieer#33]
When the disk is full, gmailier overwrites its file with an empty one and then throws an exception that the disk is full. It should probably write to a temporary file and rename it instead.

**Comment by julian-klode** [comment]
(Same for all files, really)

**Comment by julian-klode** [comment]
The first fix is easy:

```diff
diff --git a/lieer/local.py b/lieer/local.py
index 70f8cc9..889b3c7 100644
--- a/lieer/local.py
+++ b/lieer/local.py
@@ -77,8 +77,9 @@ class Local:
       self.json['account'] = self.account
       self.json['timeout'] = self.timeout
 
-      with open (self.state_f, 'w') as fd:
+      with open (self.state_f + ".new", 'w') as fd:
         json.dump (self.json, fd)
+      os.rename(self.state_f + ".new", self.state_f)
 
     def set_last_history_id (self, hid):
       self.last_historyId = hid
```

The handling in store() is wrong generally: It should first write the message to tmp/ and then move it into cur/ really (actually, it'd have to go via new, but you can't have flags there, so ...).

**Comment by julian-klode** [comment]
So I'd probably just build a helper class here that gives an atomic file inside tmp/ when you open() it, and when it's closed renames that for you, that's the best abstraction really.

**Comment by gauteh** [comment]
In the notmuch system i think it should just go directly in cur. Good
suggestions, do you have a chance to make a PR?



lør. 1. jul. 2017 kl. 23.54 skrev Julian Andres Klode <
notifications@github.com>:

**Comment by julian-klode** [comment]
Yeah, sure, I can send a pull request later.

**Comment by gauteh** [comment]
Fixed in master.
