### ISSUE TITLE
Weird corner cases with neomutt moving unread emails from cur/ to new/

### ISSUE THREAD

**Issue by julian-klode** [gauteh/gmailieer#41]
So, (neo)mutt will apparently move unread emails from cur/ to new/ when marking them as trash (for example, any other label should do the trick as well), gmailieer then just says: Not in the repo.

**Comment by gauteh** [comment]
Julian Andres Klode writes on september 10, 2017 12:18:
> So, (neo)mutt will apparently move unread emails from cur/ to new/ when marking them as trash (for example, any other label should do the trick as well), gmailieer then just says: Not in the repo.

The check-in-maildir assumed the file was in cur/, fixed to check for 
maildir-root.

**Comment by julian-klode** [comment]
Thanks, that seems to work :) :+1:
