### ISSUE TITLE
Initial `push` (after `pull`) hits API limits

### ISSUE THREAD

**Issue by the-kenny** [gauteh/gmailieer#57]
Hello,

I successfully moved two of three accounts to gmailieer. The problem is with the third and biggest account (roughly 200.000 messages):

I can successfully `init` and `pull` the messages, but a following `push` or `sync` will get throttled more and more and finally stop as gmailieer can't reduce the batch size any further.

Is there something I can do about this?

**Comment by gauteh** [comment]
Moritz U. writes on desember 9, 2017 16:45:
> Hello,
> 
> I successfully moved two of three accounts to gmailieer. The problem is with the third and biggest account (roughly 200.000 messages):
> 
> I can successfully `init` and `pull` the messages, but a following `push` or `sync` will get throttled more and more and finally stop as gmailieer can't reduce the batch size any further.
> 
> Is there something I can do about this? 
> 

There's is also a time based throttling, I think it gets better if you 
wait 24 hours. I set the min batch size to 1, it should keep going - but 
probably very slowly! You can try your own API key, but there are also 
per-account limits.

- Gaute

**Comment by the-kenny** [comment]
Thanks for the quick answer. I don't my own API key would help (can't login into the web interface either during the throttling). I'll just try again in 24 hours or so. 

Thanks!
