### ISSUE TITLE
Fetching all the metadata every time?

### ISSUE THREAD

**Issue by fagerbua** [gauteh/gmailieer#58]
Each time I run "gmi sync" it takes several minutes to fetch metadata for some 70,000 items. Is this intended behavior or is it supposed to be faster once the initial sync has been completed?

**Comment by gauteh** [comment]
Yes, faster. Must be some errors so that it doesn’t complete.

tir. 12. des. 2017 kl. 13:49 skrev fagerbua <notifications@github.com>:

**Comment by gauteh** [comment]
Try to do only pull first. Until no more changes are pulled

tir. 12. des. 2017 kl. 14:43 skrev Gaute Hope <eg@gaute.vetsj.com>:

**Comment by fagerbua** [comment]
Thanks, that did the trick!

**Comment by gauteh** [comment]
👍

tir. 12. des. 2017 kl. 15:09 skrev fagerbua <notifications@github.com>:
