### ISSUE TITLE
Use wd instead of wd/mail

### ISSUE THREAD

**Issue by mjg** [gauteh/gmailieer#59]
Currently, gmi puts the maildir store into a subdirectory `mail` of the current working directory. This is suboptimal when you want to have your gmi-managed maildir and other maildirs (synced via mbsync or offlineimap, say) under the same maildir root:

    mailroot/imapaccount/cur
    mailrrot/imapaccount/...
    mailroot/gmailaccount/mail/cur
    mailroot/gmailaccount/mail/...

This ends up as folders `imapaccount` and `gmailaccount` at the root level, but all that `gmailaccount` has is an extra unnecessary subfolder `mail` that contains all mails (when `imapaccount` contains its imap folders).

gmi's json files need to be ignored by notmuch anyways. Therefore, I suggest to put the maildir directly under the workdir (omit `/mail`), maybe based on some config setting. This could help maildir based MUAs (though notmuch based is preferred, I know).

**Comment by gauteh** [comment]
Yeah - I guess - is there any maildir-limitations / caveats on having other files in the maildir-root (will some maildir-syncer delete gmi files?)?

We would have to use versioned repository-state files from now on then.

**Comment by gauteh** [comment]
It would also be relatively easy to use `gmi` in pull mode without notmuch, I don't know if that is any point. There are other tools that also do that.

**Comment by mjg** [comment]
I've been running with a local patch for a while now and didn't notice any side effects - besides sync sometimes requiring two calls (content first, then metadata), but I don't think that's related.
On the other hand, I've almost settled for alot instead of (neo)mutt as the MUA, so paths don't matter much any more :)

**Comment by gauteh** [comment]
Michael J Gruber writes on februar 25, 2018 20:06:
> I've been running with a local patch for a while now and didn't notice any side effects - besides sync sometimes requiring two calls (content first, then metadata), but I don't think that's related.

Cool, I guess the biggest issue is migration, would be happy to include 
a patch that also accounts for that.


> On the other hand, I've almost settled for alot instead of (neo)mutt as the MUA, so paths don't matter much any more :)
> 

Ok, then I am going to close this issue untill it offends someone again ;)
