### ISSUE TITLE
Replied and Passed maildir flags are not pulled

### ISSUE THREAD

**Issue by RobinJadoul** [gauteh/gmailieer#60]

**Comment by gauteh** [comment]
Do you have maildir flag sync enabled for notmuch?

**Comment by RobinJadoul** [comment]
Yes, unread syncs properly, but neither in the maildir filenames or the
notmuch tags do the P or R flag show up properly (after initial or other
sync)

**Comment by gauteh** [comment]
I see that both passed and replied are ignored in local.py, I no longer
remember if there was a rationale for that - but suspect that gmail does
not allow them to be added manually. Maybe they should still be pulled
though. You can try to remove them from there and see what happens, but it
could result in them
being removed where you have added them manually.

lør. 20. jan. 2018 kl. 13:23 skrev Robin Jadoul <notifications@github.com>:

> Yes, unread syncs properly, but neither in the maildir filenames or the
> notmuch tags do the P or R flag show up properly (after initial or other
> sync)
>

**Comment by RobinJadoul** [comment]
It seems gmail doesn't consider this proper 'labels' (at least, they don't show up in `remote.labels`) and as such, it doesn't send them along when querying.
My thunderbird on the other hand, seems to pull these flags fine via IMAP.

**Comment by gauteh** [comment]
I think the labels should be pushed to gmail if you remove them from 
local.py:ignore_labels (if you add them manually). If GMail doesn't add 
them remotely, then they won't be pulled either.

**Comment by RobinJadoul** [comment]
I'm specifically talking about the Maildir flags (`P` or `R`, as they are appended to the maildir filenames), corresponding to the IMAP `$Forwarded` and `\Answered` flags. Known in notmuch as the `passed` and `replied` tags (see also https://notmuchmail.org/special-tags/)

These don't get synced in any direction (pushing them is possible by removing those tags from the list in `local.py`, but that isn't the point). I'm looking for a way to have `tag:replied` and `tag:passed` properly populated in my notmuch database (because right now, this isn't happening)

Looking at the API docs, it seems however that the gmail API doesn't offer this information (though it is accessible via IMAP). Unless you know of/can find another solution...

Another option might be only syncing the `[Gmail]/All Mail` folder over IMAP (with something like offlineimap or mbsync), and then syncing the flags with gmailieer, but I'm not sure how easily that would be achieved.

**Comment by gauteh** [comment]
Robin Jadoul writes on januar 22, 2018 13:36:
> Looking at the API docs, it seems however that the gmail API doesn't offer this information (though it is accessible via IMAP). Unless you know of/can find another solution...

That settles it then - if the GMail API doesn't provide it, we can't do 
much about it. Notmuch special tags are ignored to avoid causing massive 
syncing since they are added automatically by notmuch (or clients). I 
guess this behaviour could be debated, but it probably wouldn't make any 
difference on the IMAP / maildir flags.
 
> Another option might be only syncing the `[Gmail]/All Mail` folder over IMAP (with something like offlineimap or mbsync), and then syncing the flags with gmailieer, but I'm not sure how easily that would be achieved.

That's the old approach I used with `abunchoftags`, not maintained 
anymore.
