### ISSUE TITLE
After initial pull, too many messages have inbox tag

### ISSUE THREAD

**Issue by fikovnik** [gauteh/gmailieer#63]
This is my `post-new` hook (the only hook I have):
```
#!/bin/sh

# immediately archive all messages from "me"
notmuch tag -new -- tag:new and from:email@domain

# finally, remove new
notmuch tag -new -- tag:new
```
and my `.notmuch_config`:
```
[database]
...
[user]
...
[new]
tags=new
ignore=*.json;
[search]
exclude_tags=deleted;spam;
[maildir]
synchronize_flags=true
[crypto]
gpg_path=gpg
```

After the first full pull (gmi pull), I see about >80k messages tagged with inbox while gmail shows me only 1700? I guess I miss something, but I don't understand the discrepacy between the numbers?

**Comment by gauteh** [comment]
Did you try to click next page enough times in gmail? The estimates there
are really bad and they will often grow when you reach the alleged limit.
(You can enter a pageid manually to make bigger jumps in the url once you
see the pattern)



tor. 22. feb. 2018 kl. 15:15 skrev Filip Krikava <notifications@github.com>:

**Comment by fikovnik** [comment]
Yes, I tried and the estimate was correct. I see the same number when I sync over IMAP with nbsync.

**Comment by gauteh** [comment]
Hm, weird.. does the rest of the labels / tags match? Did you start with a completely fresh notmuch db / maildir?

**Comment by fikovnik** [comment]
I decided to remove everything and start over. This time the number is much closer. Btw: the full sync of 160k (11G) took roughly the same ~2hours.

**Comment by gauteh** [comment]
Ok, good!


Filip Krikava writes on februar 23, 2018 13:25:
