### ISSUE TITLE
gmi init breaks with error: "ImportError: No module named 'oauth2client'"

### ISSUE THREAD

**Issue by m2habert** [gauteh/gmailieer#66]
I have next to zero knowledge of these kind of "python problems".  I tried to do eveything by the book, however: selected py36 trough macports' `sudo port select --set python python36`, same with pip, installed oauth2 with `pip --upgrade` ...

Everything seemed to have gone fine. Then, when I tried  `gmi init my.account@gmail` : 

```
Traceback (most recent call last):
  File "/Users/m2habert/gitRepo/gmailieer/gmi", line 4, in <module>
    from lieer import Gmailieer
  File "/Users/m2habert/gitRepo/gmailieer/lieer/__init__.py", line 1, in <module>
    from .gmailieer import *
  File "/Users/m2habert/gitRepo/gmailieer/lieer/gmailieer.py", line 8, in <module>
    from    oauth2client import tools
ImportError: No module named 'oauth2client'
```

I've tried googling the error message, but couldn't make heads or tails of anything (it seems all related complaints are posted by developers programming their own APIs, nothing like a software user with installation problems)

¿Can anybody point me to the right direction? Thanks
Using MacOS 10.11.6

**Comment by m2habert** [comment]
addendum : if I try the "import" thru the command-line it seems to be working:

```
$ python
Python 3.6.4 (default, Dec 21 2017, 20:32:22)
[GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from oauth2client import tools
>>>

```

**Comment by gauteh** [comment]
You need the packages:

* `google_api_python_client` (sometimes `google-api-python-client`)
* `oauth2client`

Check the README for more dependencies. Make sure they are installed for 
the python version you are using.

**Comment by m2habert** [comment]
I installed them, as described above. When opening `/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages`
 
you can clearly see BOTH packages installed there. I'm not sure that was the problem. Anyway, they are working after uninstallation of python 3.4; new problem was notmuch package (≈ python bindings?), also noted above.

Update: I was not able to install notmuch with python bindings thru macports and couldn't find directions to install them otherwise. But I found a notmuch package in homebrew's `/usr/local/Cellar/notmuch/0.26/lib/python2.7/site-packages/`
and copied it to macports' py36's packages' dir... And gmailieer is now working(!), it seems.

**Comment by gauteh** [comment]
Then probably python 3.4 was default and gmi was launched with that.

**Comment by gauteh** [comment]
Hm, ok, I don't know. Good that you got it going though!
