### ISSUE TITLE
Provide gmailieer a list of tags to ignore in push

### ISSUE THREAD

**Issue by stdbull** [gauteh/gmailieer#80]
Hi. I was thinking it would be useful if we could provide gmailieer a text file containing tags to ignore when doing a push. For me, I use notmuch-emacs much more than the Gmail web interface and it would be useful for me to have a notmuch-emacs 'view' using tags that I'm not bothered about pushing back to Gmail. For implementation, I was thinking along the lines of an option to specify a path to a text file that contained one tag per line and then append this to ignore_labels[ ].
What do you think? Definitely an enhancement :-)

**Comment by gauteh** [comment]
Absolutely :) In fact an issue already exists: #32 and an implementation was attempted in #62, but it hit a bunch of snags since it was also doing label/tag translations. Just custom ignoring shouldn't be too hard.

Closing as duplicate.

**Comment by gauteh** [comment]
See #81.
