### ISSUE TITLE
Specify a directory other than .mail?

### ISSUE THREAD

**Issue by vikasrawal** [gauteh/gmailieer#86]
Is it possible to specify a directory other than .mail?

Vikas

**Comment by gauteh** [comment]
Vikas Rawal writes on July 18, 2018 11:30:
> Is it possible to specify a directory other than .mail?

Gmailieer uses the current dir it is invoked from - but it must be in 
the notmuch database. You can set up notmuch wherever you want.

**Comment by vikasrawal** [comment]
gmi init my.email@gmail.com seems to create a .mail in the current directory which is supposed to hold the maildir.

**Comment by gauteh** [comment]
Vikas Rawal writes on July 18, 2018 16:42:
> gmi init my.email@gmail.com seems to create a .mail in the current directory which is supposed to hold the maildir.
> 

Oh, right - I thought you referred to the example in the README. No, not 
customizable. But the top-folder is designed to be exclusively used by 
gmi. So I create a sub-folder for gmi, enter it and then run gmi init.
