### ISSUE TITLE
Question only: can it be used without notmuch? And with no less-secure apps enabled? 

### ISSUE THREAD

**Issue by edumerco** [gauteh/gmailieer#90]
Hello Gauteh. 

I have a Google based account in a domain that does not enable less-secure apps access. Because of that, I can't use mbsync to sync this account. 

Can I use gmailieer to sync this one? Even if I don't use notmuch, if it syncs the mails to a standard maildir it's ok for me. 

In any case, thanks a lot for sharing your hard work. :)

Best regards...

**Comment by gauteh** [comment]
Eduardo Mercovich writes on September 3, 2018 3:02:
> Hello Gauteh. 
> 
> I have a Google based account in a domain that does not enable less-secure apps access. Because of that, I can't use mbsync to sync this account. 

I think so!

> Can I use gmailieer to sync this one? Even if I don't use notmuch, if it syncs the mails to a standard maildir it's ok for me. 

Requires notmuch to detect local changes, currently not possible to use 
in only "pull"-mode. You can set up notmuch and not use it though. The 
output is still like a maildir. Note that you cannot modify the maildir 
(add, delete, move files). You can change maildir flags, but remember to 
run notmuch new before running gmailieer again.

**Comment by edumerco** [comment]
Hello Gaute.

> > Can I use gmailieer to sync this one? Even if I don't use notmuch, if it syncs the mails to a standard maildir it's ok for me.

> Requires notmuch to detect local changes, currently not possible to use in only "pull"-mode. You can set up notmuch and not use it though. The
> output is still like a maildir.

"Like" a maildir? ;)
What is the difference?

> Note that you cannot modify the maildir (add, delete, move files). You can change maildir flags, but remember to run notmuch new before running gmailieer again.

Ah, I may be in trouble then... I have mu4e here, so the -potential-
idea was to use it to sync the maildir instead of mbsync.
If I got it right, it can't be used for this...


-- 
eduardo mercovich

 Donde se cruzan tus talentos
 con las necesidades del mundo,
 ahí está tu vocación.

**Comment by gauteh** [comment]
Eduardo Mercovich writes on September 3, 2018 14:35:
> Hello Gaute.
> 
>> > Can I use gmailieer to sync this one? Even if I don't use notmuch, 
>> > if it syncs the mails to a standard maildir it's ok for me.
> 
>> Requires notmuch to detect local changes, currently not possible to 
>> use in only "pull"-mode. You can set up notmuch and not use it 
>> though. The
>> output is still like a maildir.
> 
> "Like" a maildir? ;)
> What is the difference?

None. Should be correct maildir.

>> Note that you cannot modify the maildir (add, delete, move files). 
>> You can change maildir flags, but remember to run notmuch new before 
>> running gmailieer again.
> 
> Ah, I may be in trouble then... I have mu4e here, so the -potential-
> idea was to use it to sync the maildir instead of mbsync.
> If I got it right, it can't be used for this...
> 

If you need to add or delete messages from the maildir, yes probably.

**Comment by edumerco** [comment]
Hello.

[...] 
>>> Note that you cannot modify the maildir (add, delete, move 
>>> files). You can change maildir flags, but remember to run 
>>> notmuch new before running gmailieer again.

>> Ah, I may be in trouble then... I have mu4e here, so the 
>> -potential- idea was to use it to sync the maildir instead of 
>> mbsync. If I got it right, it can't be used for this...

> If you need to add or delete messages from the maildir, yes 
> probably.

Ah, pity...

Anyway, thanks a lot for sharing your work. :)

Best...


-- 
eduardo mercovich

 Donde se cruzan tus talentos 
 con las necesidades del mundo, 
 ahí está tu vocación. 
 (Anónimo)

**Comment by edumerco** [comment]
Hello.

[...] 
>>> Note that you cannot modify the maildir (add, delete, move 
>>> files). You can change maildir flags, but remember to run 
>>> notmuch new before running gmailieer again.

>> Ah, I may be in trouble then... I have mu4e here, so the 
>> -potential- idea was to use it to sync the maildir instead of 
>> mbsync. If I got it right, it can't be used for this...

> If you need to add or delete messages from the maildir, yes 
> probably.

Ah, pity...

Anyway, thanks a lot for sharing your work. :)

Best...


-- 
eduardo mercovich

 Donde se cruzan tus talentos 
 con las necesidades del mundo, 
 ahí está tu vocación. 
 (Anónimo)
