### ISSUE TITLE
only fetch recent mail (limit disk size)

### ISSUE THREAD

**Issue by mturquette** [gauteh/gmailieer#93]
Some IMAP fetching solutions offer the capability to limit what mail is fetched based on criteria like message (or thread) age, or by an on-disk size limit.

Is there a way to do this with gmailieer? Maybe by playing games with historyId?

My use case is that I'm low on disk space on my laptop and I would love to only have the previous 30 days of mail sync'd. On my workstation I want everything sync'd (the current default behavior of gmailieer).

Any ideas? Is this already supported?

**Comment by gauteh** [comment]
Michael Turquette writes on October 4, 2018 7:28:
> Is there a way to do this with gmailieer? Maybe by playing games with historyId?

Maybe you can do this by changing the GMail query in remote.py? Not sure 
about the implications of this so proceed with caution.

**Comment by gauteh** [comment]
Did you test with a search query limiting by e.g. date?

**Comment by mturquette** [comment]
It's on my todo list. I'm traveling for work now, so I'll either do it
when I return home or I'll do it sooner if I run out of disk space ;-)

**Comment by gauteh** [comment]
Closing, not a big priority.
