### ISSUE TITLE
suggest: add option to specify file extension

### ISSUE THREAD

**Issue by tbrk** [gauteh/gmailieer#98]
I am the author of [tbrk/muttlight](https://github.com/tbrk/muttlight) which improves the indexing of messages in maildirs on MacOS using the "Spotlight" feature.

This software must be registered with the OS to treat the files stored in maildirs. The simplest way to associate files on MacOS with the applications that treat them, i.e., for opening or indexing, is to register file extensions. The fetchmail and getmail programs create maildir files with the extension `.mbox:2,DFPRST` or `.<hostname>:2,DFPRST` for all combinations of the maildir status flags `DFPRST` and where the current `<hostname>` is sometimes used to facilitate synchronization of maildir folders across different machines.

I don't use gmailieer myself, but I have been contacted by someone who does asking whether he could also use muttlight. Unfortunately, I do not know how to do this reliably without using file extensions.

So, would it please be possible to add a configuration option whereby gmailieer would add a period and the current hostname before the maildir version and status flags in generated filenames?

**Comment by gauteh** [comment]
Hi,

gmailieer cannot be used without notmuch, if still useful adding a configurable portion would be possible. Since we already have to remove the last portion of the filename this should not have any additional performance effect. The maildir flags are not static though, would that not change the extension?

Regards, Gaute

**Comment by tbrk** [comment]
Yes, I think it would be useful. I use mutt with [mu](https://www.djcbsoftware.nl/code/mu/) on MacOS and having Spotlight indexing and preview is still very useful in the GUI. I expect the same to be true for notmuch on MacOS.

The maildir flags are indeed problematic. In fact, they are one of the problems that muttlight tries to solve. The solution is not especially clever: we simply register all 64 combinations of the flags for all user-specified hostnames. It seems to work quite well in general.

**Comment by gauteh** [comment]
Ok, this should not be difficult. I dont have the chance to do this in the next days, but happy to review a PR if someone wants to give it a shot.

**Comment by tbrk** [comment]
I've had a shot at adding this feature. I've done some testing, but I'm a complete gmailieer/notmuch newbie so my patch probably needs a careful review.

I've assumed that synchronized filenames never usually contain a period ("."). Is this reasonable?

**Comment by gauteh** [comment]
Fixed in #99
